[package]
name = "double_pendulum_rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "visualize"
path = "src/visualize.rs"
[[bin]]
name = "visualize_anim"
path = "src/visualize_anim.rs"

[dependencies]
plotters = "0.3"
rayon = "1.10"
serde = { version = "1.0", features = ["derive"] }
csv = "1.1"
num_cpus = "1.17"
image = "0.24"
gif = "0.13"